### ISSUE TITLE
Complete RTM API

### ISSUE THREAD

**Issue by christhekeele** [BlakeWilliams/Elixir-Slack#11]
In addition to sending messages, the Slack RTM API allows a couple of other actions over the socket:

- [Typing indicators](https://api.slack.com/rtm#typing_indicators)
- [Pinging](https://api.slack.com/rtm#ping_and_pong)
- [ID tagging and confirmation](https://api.slack.com/rtm#sending_messages)

For robustness I propose adding support for these.

#### Typing Indicators

- `Slack.indicate_typing/2`

  Accepts a channel and a `Slack.State`. Activates the bot's typing indicator in that channel.

#### Pinging

Right now pinging is simulated in [this function](https://github.com/BlakeWilliams/Elixir-Slack/blob/d662f6c7c7bffd6a1f42712e5b1562464d195b2b/lib/slack.ex#L110..L112):

```elixir
def websocket_handle({:ping, data}, _connection, state) do
  {:reply, {:pong, data}, state}
end
```

Rather than have a no-op, it'd be nice if it actually sent the ping to the server. To accommodate this, I propose:

- `Slack.send_ping/1`

  Accepts a `Slack.State`. Pings the slack server.

- `Slack.send_ping/2`

  Accepts a `Slack.State` and a Dict implementation. Pings the slack server with the extra data.

- `Slack.handle_pong/3`

  Accepts a response, a `Slack.State`, and the server state. Of course, the response is expected to be of type pong with any extra data sent passed back in.
  

#### ID Tagging and Confirmation

Every payload you send slack will respond with a confirmation message. If you send an ID with it, the specific confirmation for that payload will return with the same ID.

Currently, `Slack.send_message/3` doesn't allow injecting any extra parameters into the JSON–namely, an ID. This would be handy for a few of my usecases. Additionally, it'd be nice to have for the ping API above.

Even if we could tag outgoing payloads with IDs, we'd have no way to handle the incoming response confirmations right now. Maybe we could make a `Slack.handle_confirmation` mechanism for receiving them somehow. I'm less sure what the API for this feature might look like, though. If implemented, `Slack.handle_pong` would probably be subsumed by it.

**Comment by BlakeWilliams** [comment]
Hey Chris, thanks for putting this together. This would probably be better suited as individual issues per feature-request instead of one giant issue since that's much harder to track and work through.

I'd also suggest that if any of these are high priority to you to submit a pull request with the feature and appropriate test. I think you can also take advantage of the first two immediately via [send_raw](https://github.com/BlakeWilliams/Elixir-Slack/blob/d662f6c7c7bffd6a1f42712e5b1562464d195b2b/lib/slack.ex#L154-L156)

If you send a ping now, I *think* you should get an appropriate `handle_message` response from it. eg: `send_raw(JSX.encode(%{id: "abc123", type: "ping", time: 1403299273342"}), slack)` would probably work. I don't think that would require a special `handle_pong` message since `handle_message` should already cover that case.

As for tagging and confirmation, I think it would make sense to allow `send_message` to take an optional id parameter to send over to Slack but keeping track of it should be the job of the application, not Elixir-Slack (except making sure `handle_message` also gets the id).

**Comment by christhekeele** [comment]
1. I'll split this up into separate issues.
1. I'm already working on a PR for `indicate_typing`, my immediate interest. :)
1. I'll confirm the current ping situation before creating an issue.
1. Agreed–I think the application should track ids, not us. On the other hand, I have a nascent idea for how we could make it easier, which I'll discuss on the appropriate issue. This feature is my second priority.
1. Once all this is implemented, we ought to have 100% parity with Slack's RTM API–would you want `send_raw` to become private at that point?

**Comment by BlakeWilliams** [comment]
Thanks for splitting that up.

As for 5, I don't think we'd ever want to make it private. It's exposed for situations when you want to do something slightly odd or Slack releases a new feature you've gotta have now.

**Comment by christhekeele** [comment]
I see the source of some of my confusion, now. `Slack.send_message` is explicitly typed to `[ type: "message" ]`, while `Slack.handle_message` is not–although I assumed it was.

**Comment by BlakeWilliams** [comment]
Yeah, that could probably be renamed for clarity. I'd be open to having `handle_message` renamed to `handle_reply`, but `handle_message` would need to print a deprecation warning and still work for a few releases.
