### ISSUE TITLE
Threading support

### ISSUE THREAD

**Issue by Bockit** [BlakeWilliams/Elixir-Slack#132]
Are there are any plans to support threading in the rtm api
? https://api.slack.com/docs/message-threading

I started looking into it and I *think* you can get by with send_raw as a workaround, but I was wondering if there were plans for api support. I wouldn't know how the api would need to change to support it.

**Comment by BlakeWilliams** [comment]
I'd happily accept a PR that builds in threading support, but I have no need for it myself so it's not really in the roadmap.

**Comment by mmartinson** [comment]
@Bockit it's fairly straightforward to use the web API wrapper in this library to post messages to a channel instead of using the socket connection if you don't want to do the implementation there. There is an example payload in the doc you linked. I have found it best for my application to use the socket connection for receiving events, but do all my posts and updates through the web API.

**Comment by Bockit** [comment]
That's a good strategy, thanks for the heads up.
