### ISSUE TITLE
Supervisor tree issue with 1.5

### ISSUE THREAD

**Issue by vishal-h** [BlakeWilliams/Elixir-Slack#142]
This pertains to closed issue #109. With the recent release of Elixir 1.5, I get the error
The module {some_name} was given as a child to a supervisor but it does not implement child_spec/1. If you own the given module, please define a child_spec/1 function that receives an argument and returns a child specification. If not, pass a map child specification instead of the given module to the supervisor. See the Supervisor module for documentation.
Is there a work around?

**Comment by philwade** [comment]
I just figured out the work around for this (with the help of the error message), you can pass a child specification map so your app start looks like this:

    def start(_type, _args) do
        children = [
             %{
               id: Slack.Bot,
               start: {Slack.Bot, :start_link, [MyApp.SlackModule, [], "YOUR-TOKEN"] }
             }
        ]

        opts = [strategy: :one_for_one, name: MyApp.Supervisor]
        Supervisor.start_link(children, opts)
     end

Might try to find some time to open a pull request for `child_spec/1`, since I assume it just creates that dictionary out of the `{ Slack.Bot, args}` tuple.
