### ISSUE TITLE
Change base handler from `handle_message`

### ISSUE THREAD

**Issue by christhekeele** [BlakeWilliams/Elixir-Slack#15]
#### Extracted from #11

For clarity between message-type responses and other events, the base event handler should be changed from `handle_message` to something more general.

This change should be backwards compatible and issue a deprecation warning.

#### Discuss
Preference in `handle_reply` vs `handle_response` vs `handle_event`, or something else, for the generic handler?

**Comment by BlakeWilliams** [comment]
I agree. I like `handle_reply`. If you want to open a PR where `handle_message` is renamed to `handle_reply` that'd be awesome. I'd keep `handle_message` too but print a deprecation warning and calling through to `handle_reply` if possible.

**Comment by sircharleswatson** [comment]
I know this is a little old _but_ I think it should be `handle_event` rather than `handle_reply`. This more closely follows the terminology that the [Slack RTM docs](https://api.slack.com/rtm#events) follow. There is a `message` event that is what we generally use so I think `handle_event` would be much better. `handle_reply`, just the name, makes me assume we already sent a message to the client and it is "replying".

**Comment by BlakeWilliams** [comment]
Resolved in #89
