### ISSUE TITLE
user.name being replaced by user.profile.display_name

### ISSUE THREAD

**Issue by nmohoric** [BlakeWilliams/Elixir-Slack#169]
Any plans for handling this as it seems like the name attribute is being deprecated?
https://api.slack.com/changelog/2017-09-the-one-about-usernames

There is no actual specific date of them getting rid of the name attribute but a lot of lookups rely on it, and they seem to be saying they're going to start getting rid of the old username after September 12

**Comment by agis** [comment]
@BlakeWilliams any updates on this one?

**Comment by BlakeWilliams** [comment]
I haven't had a lot of time recently to look into this. I'd happily accept a PR if someone wants to do a bit of research and figure out what's necessary to move forward.

**Comment by jameskbride** [comment]
I put together a PR to partially address this change.  See https://github.com/BlakeWilliams/Elixir-Slack/pull/188 . I say partially because according to the documentation looking up the username now requires reading `users.list` and finding the latest `user_id` match by username, which seems like a much bigger lift. 

@BlakeWilliams If you get a chance could you take a look at this and let me know what you think please?  Thanks in advance!

**Comment by BlakeWilliams** [comment]
@jameskbride Great, I was just taking a peek at one of the PR's you closed. I'll try to get around to taking a look at it today or tomorrow.

**Comment by BlakeWilliams** [comment]
Also thanks for diving in and working on these issues ✨

**Comment by jameskbride** [comment]
Thanks @BlakeWilliams, glad to help!
