### ISSUE TITLE
Outstanding PRs

### ISSUE THREAD

**Issue by jameskbride** [BlakeWilliams/Elixir-Slack#189]
Hi @BlakeWilliams,

It looks like there are some outstanding PRs that look like they're ready to merge in, and a few recent PRs that have been merged but need a release to fully realize their potential. I wanted to get your thoughts on some of these and see if we can come up with a plan to work on incorporating these changes in future releases. 

Here are some things I see that I wanted to get your opinion on:

## Merged  - Needs a Release
- https://github.com/BlakeWilliams/Elixir-Slack/pull/183: Create separate token generation instructions doc -  This has been merged but the README still contains a broken link to the instructions in the Hex documents that haven't been updated yet. 
- https://github.com/BlakeWilliams/Elixir-Slack/pull/185: Add Users.lookup_by_email to Web API -  Just needs a new release to provide the functionality.

### No conflicts, probably just needs merged in
- https://github.com/BlakeWilliams/Elixir-Slack/pull/188: Issue# 169: Deprecate Username
- https://github.com/BlakeWilliams/Elixir-Slack/pull/184: Fix rtm.connect startup issue
- https://github.com/BlakeWilliams/Elixir-Slack/pull/180: Update group topic
- https://github.com/BlakeWilliams/Elixir-Slack/pull/155: Add Groups.replies and Channels.replies to the web api

### Conflicts
- https://github.com/BlakeWilliams/Elixir-Slack/pull/173 - dont fail application is Slack fails to connect - Needs to be brought up to speed with `master` and to have a test added per your request.
- https://github.com/BlakeWilliams/Elixir-Slack/pull/125 - Adding new method ProfileSet to Slack.Web.Users. - There was a comment about not swapping JSX and HTTPoison in this PR, but it looks like the project has already moved to HTTPoison. Might still need to have JSON files updated.

### Conflicts - Needs Architecture Resolution
- https://github.com/BlakeWilliams/Elixir-Slack/pull/172 - Send message with threaded replies to messages in channels
- https://github.com/BlakeWilliams/Elixir-Slack/pull/64 - Lets Slack detect message confirmations if optional message ID is given.

These two touch a lot of the same code in `sends.ex` and probably need some thought about how we want to handle the additional params that being passed.

<hr />
I'm not sure if the original authors are still interesting in their changes, but I'd be glad to help out with resolving the conflicting issues.  I'm thinking we get the conflicting branches up to date with `master`, resolve the architecture questions, and we can get them merged in. I can't really help with the actual releases, but I figure I can take some of the lift off of your shoulders for managing the code conflicts. 

Let me know what you think and I'll look forward to working with you on this project. Also thanks again for everything you've done, this project wouldn't exist without you.

**Comment by BlakeWilliams** [comment]
Thanks for writing this up! The project definitely hasn't gotten as much attention from me as it should lately.

I definitely need to do a release and will get one out shortly.

* #188 looks good, need to merge that in.
* #184 someone had concerns on the PR last I checked. I really don't have a slack bot set up right now that I can use for testing the changes. If someone could verify that things still work with a real bot I'd feel comfortable merging it.
* #180 Just gotta merge it in
* #155 Same thing, just need to merge it in.

I've been a little hesitant of merging new web API features since Slack no longer supports updating that JSON documentation repo last I checked but the community has been ❤️ and filling them in themselves so I think they should just start getting merged.

The PR's with conflicts seem fine once they're resolved. 👍 

Agreed on thinking through the two that need resolution.

**Comment by BlakeWilliams** [comment]
All that being said, if you'd be interested in putting in the time to get all of those up-to-date and test them with a bot to ensure they're good to go that'd be amazing and I'd definitely appreciate the help. I'll work on being a bit more responsive on the repo now that things are a little less hectic.

**Comment by jameskbride** [comment]
No worries about responsiveness, everyone is busy and I know how much of a time sink projects like this can be, especially when you're the only one managing it 😄 

I'd be glad to help out.  I'll start looking at testing and maybe take a look at how to resolve #172 and #64. 

Thanks for getting a number of those features merged in!

**Comment by yordis** [comment]
@BlakeWilliams are you interested in passing the ownership or adding contributors to the project?

Some people may be able to help you in taking care of the package.

**Comment by soriyath** [comment]
I've created this PR: https://github.com/BlakeWilliams/Elixir-Slack/pull/204
to solve this issue: https://github.com/BlakeWilliams/Elixir-Slack/issues/193

**Comment by BlakeWilliams** [comment]
> @BlakeWilliams are you interested in passing the ownership or adding contributors to the project?

I'd be happy to give contribution status to anyone who's passionate about the project. If anyone's feeling energized about Elixir and Slack please reach out. I would definitely appreciate some help maintaining things.

I think this issue is mostly resolved, so closing for now. If I missed anything or if anything needs attention please ping me in the issue/PR. :)
