### ISSUE TITLE
Stub Version for Testing?

### ISSUE THREAD

**Issue by mwean** [BlakeWilliams/Elixir-Slack#92]
Hey, I'm really enjoying the package, but I'm having problems testing my bot since it makes real connections to Slack each time. I was wondering if we could add a way to stub the Slack connection. I'm already mocking things like `Slack.Sends.send_message`, but the initial connection happens before I can stub it.

It looks like we would need to stub out `Slack.Rtm.start` to return the initial state, and add a fake websocket client. I'd be happy to implement this, but I'm not sure how best to go about it. Any ideas or direction would be appreciated.

**Comment by BlakeWilliams** [comment]
Glad you like it! I also think this is an issue, but I'm not sure that stubbing is the best answer. I'm hesitant to build stubbing into the libs API.

I think there's a few potential solutions, like [ExVCR](https://github.com/parroty/exvcr) and [`mock`](https://github.com/jjh42/mock).

Would not starting the bot in the test environment be a solution?

**Comment by mwean** [comment]
I'm already using mock for things like `Slack.Sends.send_message`, but ExVCR is a good idea. It looks like I need to wrap the initial http request with VCR, so I'd have to start the bot inside the test. I'm not sure how I can do that, though because the bot is started as part of the supervision tree of my app. I don't know how to make that conditional for the test env.

**Comment by nickve28** [comment]
Why not use the principle of explicit contracts described here? http://blog.plataformatec.com.br/2015/10/mocks-and-explicit-contracts/
In that case you can specify your own test slack client module and use that.


Otherwise, if you're not testing the specifics of that slack client, you could always run the test without starting the supervision tree. eg:  mix test --no-start

**Comment by mwean** [comment]
If I understand correctly, the test slack client with explicit contracts is what I was initially suggesting (although probably explained poorly). I was imagining in-memory versions of `Slack.Bot`, `Slack.Rtm`, etc. that could be used in tests. I'll try to implement something like that and see how it goes. Thanks!

**Comment by nickve28** [comment]
Yes it is somewhat similar, although since you were referring to mocking I was under the impression you were using a library such as meck.

With explicit contract you use more of an Inversion of control pattern, where you can decide what module to use in your application, such as:

```
@slack_client Application.get_env(:my_application, :messaging_client)
```

and then in your config of test you'd have something like:

```
config :my_app, war_api: MyApp.Clients.MockSlackClient
```

This way, you can implement that module yourself and make predictable outcomes based on, for example, pattern matching like.

As on the question, I'm also not sure if it is the library that should support this, I think it's better to define your own stub client.

Hope it helps, good luck! :)

**Comment by BlakeWilliams** [comment]
> As on the question, I'm also not sure if it is the library that should support this, I think it's better to define your own stub client.

I agree with that and think overall that's a pretty good pattern to follow. Thanks for your explanation @nickve28!

I'm closing this for now, but if that doesn't work out feel free to reopen it or open a new issue.
